// Event routing codegen (Plan 25 §8). Turns the composer's resolved event edges
// (wiring.events = [{event, from, to}]) into an `eventName -> [consumerModule]`
// table. The runtime queue consumer (connection-contract/runtime/event-consumer)
// looks up this table to fan a verified envelope out to its consumers.

export function eventRoutes(wiring) {
  const routes = {};
  for (const edge of wiring?.events ?? []) {
    (routes[edge.event] ??= new Set()).add(edge.to);
  }
  const out = {};
  for (const event of Object.keys(routes).sort()) {
    out[event] = [...routes[event]].sort();
  }
  return out;
}

export function generateEventRouter(wiring) {
  const routes = eventRoutes(wiring);
  return `// Generated by microservices.sh event-codegen — event routing table.
// Maps each domain event to the modules that consume it. Edit module
// connections, not this file.

export const eventRoutes = ${JSON.stringify(routes, null, 2)};
`;
}
