// Hook map codegen (Plan 25 §5/§8). Turns the composer's resolved hook chains
// (wiring.hooks[point] = ordered [{registrant, handler, order, kind, ...}]) into
// a `hookPoint -> ordered [{module, handler, order, kind}]` map. The producing
// module's use case feeds this chain to runHooks() at runtime.

export function hookChainMap(wiring) {
  const out = {};
  for (const point of Object.keys(wiring?.hooks ?? {}).sort()) {
    out[point] = [...wiring.hooks[point]]
      .sort((a, b) => a.order - b.order)
      .map((link) => ({ module: link.registrant, handler: link.handler, order: link.order, kind: link.kind }));
  }
  return out;
}

export function generateHookMap(wiring) {
  const chains = hookChainMap(wiring);
  return `// Generated by microservices.sh hook-codegen — ordered cross-module hook
// chains keyed by hook point. Edit module connections, not this file.

export const hookChains = ${JSON.stringify(chains, null, 2)};
`;
}
