// Service-mode RPC codegen (plans/24, step 2).
//
// Generates two artifacts from a module's `rpc` contract:
//   - generateRpcEntrypoint: the callee `WorkerEntrypoint` subclass. Each rpc
//     method is exposed, the caller token is verified, and the required scope is
//     enforced before the module use case runs.
//   - generateRpcClient: the caller-side typed interface + a dispatcher resolver
//     that reaches the service by deterministic name within the tenant scope.
//
// Embedded mode does not use these — it calls the module use cases in-process.
// Modules without an rpc contract or a service spec return null.

const SERVICE_SPECS = {
  auth: {
    pkg: "@microservices-sh/auth",
    depsImport: 'import { createD1SigningKeyStore } from "@microservices-sh/auth/adapters/d1";',
    depsExpr: "{ signingKeyStore: createD1SigningKeyStore(this.env.DB) }",
    // auth verifies its own tokens locally (it holds the keys).
    verify: "self",
  },
  customer: {
    pkg: "@microservices-sh/customer",
    depsImport: 'import { createD1CustomerRepository } from "@microservices-sh/customer/adapters/d1";',
    depsExpr: "{ customerRepository: createD1CustomerRepository(this.env.DB) }",
    // other services verify via the auth service binding.
    verify: "binding",
  },
  booking: {
    pkg: "@microservices-sh/booking",
    depsImport: 'import { createD1BookingRepository } from "@microservices-sh/booking/adapters/d1";',
    depsExpr: "{ bookingRepository: createD1BookingRepository(this.env.DB) }",
    // other services verify via the auth service binding.
    verify: "binding",
  },
  payment: {
    pkg: "@microservices-sh/payment",
    depsImport:
      'import { createD1PaymentRepository } from "@microservices-sh/payment/adapters/d1";\nimport { createStripePaymentGateway } from "@microservices-sh/payment/adapters/stripe-gateway";',
    depsExpr:
      "{ paymentRepository: createD1PaymentRepository(this.env.DB), paymentGateway: createStripePaymentGateway(this.env.STRIPE_SECRET_KEY) }",
    // other services verify via the auth service binding.
    verify: "binding",
  },
};

function pascalCase(id) {
  return id.replace(/(^|-)([a-z])/g, (_match, _sep, char) => char.toUpperCase());
}

export function rpcMethods(module) {
  // Prefer the nested connections.rpc.exposes (Plan 25); fall back to the legacy
  // flat `rpc` array during the phase-3 migration window.
  const exposes = module?.connections?.rpc?.exposes;
  if (Array.isArray(exposes)) return exposes;
  return Array.isArray(module?.rpc) ? module.rpc : [];
}

export function serviceClassName(moduleId) {
  return `${pascalCase(moduleId)}Service`;
}

export function generateRpcEntrypoint(module) {
  const methods = rpcMethods(module);
  const spec = SERVICE_SPECS[module.id];
  if (methods.length === 0 || !spec) return null;

  const className = serviceClassName(module.id);
  const methodImpls = methods
    .map((method) => {
      const hasInput = method.method !== "getJwks";
      const params = hasInput ? "input: unknown, token?: string" : "token?: string";
      const inputArg = hasInput ? "input" : "undefined";
      return `  async ${method.method}(${params}) {\n    return this.#dispatch(${JSON.stringify(method.method)}, ${inputArg}, token);\n  }`;
    })
    .join("\n\n");

  const verifyBlock =
    spec.verify === "self"
      ? `    const verified = await verifyCallerToken(token, this.#deps());`
      : `    const verified = (await this.env.AUTH.verifyToken(token)) as { ok: boolean; data?: { claims: TokenClaims }; status?: number; error?: unknown };`;

  const authImports =
    spec.verify === "self"
      ? `import { verifyToken as verifyCallerToken } from "${spec.pkg}";\nimport { requireScope } from "@microservices-sh/auth/scope";\nimport type { TokenClaims } from "@microservices-sh/auth/types";`
      : `import { requireScope } from "@microservices-sh/auth/scope";\nimport type { TokenClaims } from "@microservices-sh/auth/types";`;

  return `import { WorkerEntrypoint } from "cloudflare:workers";
import { rpcContract } from "${spec.pkg}/rpc";
${authImports}
${spec.depsImport}
import type { Env } from "./env";

// Generated by microservices.sh rpc-codegen — service-mode entrypoint for the
// ${module.id} module. Edit the module use cases, not this file.
export class ${className} extends WorkerEntrypoint<Env> {
${methodImpls}

  #deps() {
    return ${spec.depsExpr};
  }

  async #authorize(token: string | undefined, scope: string | null) {
    if (!token) {
      return { ok: false as const, status: 401 as const, error: { code: "UNAUTHENTICATED", message: "Caller token required." } };
    }
${verifyBlock}
    if (!verified.ok) return verified;
    if (scope) {
      const claims = (verified as { data: { claims: TokenClaims } }).data.claims;
      const scoped = requireScope(claims, scope);
      if (!scoped.ok) return scoped;
    }
    return { ok: true as const };
  }

  async #dispatch(method: string, input: unknown, token?: string) {
    const entry = rpcContract[method];
    if (!entry) {
      return { ok: false as const, status: 404 as const, error: { code: "UNKNOWN_METHOD", message: method } };
    }
    if (!entry.public) {
      const gate = await this.#authorize(token, entry.scope);
      if (!gate.ok) return gate;
    }
    return entry.handler(input, this.#deps());
  }
}
`;
}

export function generateRpcClient(module) {
  const methods = rpcMethods(module);
  if (methods.length === 0) return null;

  const className = serviceClassName(module.id);
  const iface = `${pascalCase(module.id)}Rpc`;
  const methodSigs = methods
    .map((method) => {
      const hasInput = method.method !== "getJwks";
      const params = hasInput ? "input: unknown, token?: string" : "token?: string";
      return `  ${method.method}(${params}): Promise<unknown>;`;
    })
    .join("\n");

  return `// Generated by microservices.sh rpc-codegen — caller-side client for the
// ${module.id} service (${className}). Reach the service by deterministic name
// within the tenant/project scope (plans/24).

export interface ${iface} {
${methodSigs}
}

export interface ServiceLocator {
  get(name: string): ${iface};
}

export function get${className}(dispatcher: ServiceLocator, projectId: string, environment: string): ${iface} {
  return dispatcher.get("app_" + projectId + "_${module.id}_" + environment);
}
`;
}
