// Agent-tool codegen — turns a module's `rpc` contract into a GOVERNED tool
// manifest: one scoped, audited, approval-gated tool descriptor per rpc method.
//
// This is the governance/metadata layer the MCP or agent runtime exposes. Input
// is validated by the module's OWN use case (its zod schema) when the rpc
// handler runs, so a descriptor carries governance — scope, public, mutation/
// confirm — not a duplicated input schema. Same method source as rpc-codegen.

import { rpcMethods } from "./rpc-codegen.js";

// A method is read-only when its name has a read prefix OR its scope ends in a
// read-class suffix. Everything else is treated as a mutation and approval-gated
// by default — over-gating is safe, under-gating is dangerous. A module can
// override per method with an explicit `mutation: true|false` on the rpc entry.
const READ_PREFIXES = ["get", "list", "read", "find", "query", "fetch", "count", "view", "describe"];
const READ_SCOPE_SUFFIX = /\.(read|list|view|observe|verify)$/;

export function isReadMethod(method) {
  if (typeof method.mutation === "boolean") return !method.mutation;
  const name = String(method.method ?? "").toLowerCase();
  if (READ_PREFIXES.some((prefix) => name.startsWith(prefix))) return true;
  if (method.scope && READ_SCOPE_SUFFIX.test(method.scope)) return true;
  return false;
}

// MCP tool names allow [A-Za-z0-9_-], so a hyphenated module id is name-safe.
export function toolName(moduleId, methodName) {
  return `${moduleId}_${methodName}`;
}

export function toolDescriptor(moduleId, method) {
  const mutation = !isReadMethod(method);
  const isPublic = Boolean(method.public);
  const scope = method.scope ?? null;
  const access = isPublic ? "public" : `requires scope ${scope}`;
  const kind = mutation ? "mutation (approval-gated)" : "read-only";
  return {
    name: toolName(moduleId, method.method),
    module: moduleId,
    method: method.method,
    scope,
    public: isPublic,
    mutation,
    requiresConfirmation: mutation,
    description: `${method.method} on the ${moduleId} module — ${kind}, ${access}.`,
  };
}

export function generateToolManifest(module) {
  const methods = rpcMethods(module);
  if (!module?.id || methods.length === 0) return [];
  return methods.map((method) => toolDescriptor(module.id, method));
}

export function generateToolManifestFile(modules) {
  const tools = (Array.isArray(modules) ? modules : [])
    .flatMap((module) => generateToolManifest(module))
    .sort((a, b) => a.name.localeCompare(b.name));

  return `// Generated by microservices.sh tool-codegen — governed agent-tool manifest.
// One scoped, audited, approval-gated tool per module rpc method. Input is
// validated by the module's own use case (its zod schema) when the rpc handler
// runs — the agent/MCP layer forwards the call. Edit module contracts, not this
// file.

export const toolManifest = ${JSON.stringify(tools, null, 2)};
`;
}
