export { moduleDefinition, manifest } from "./manifest";
export { defaultConfig, configSchema } from "./config";
export { events } from "./events";
export { permissions } from "./permissions";
export { resources } from "./resources";
export { createBooking } from "./use-cases/create-booking";
export { getAvailability } from "./use-cases/get-availability";
export { getBooking } from "./use-cases/get-booking";
export { listBookings } from "./use-cases/list-bookings";
export { rpcContract } from "./rpc";
export type { BookingRepository } from "./ports";
export type { AvailabilitySlot, Booking, Service } from "./types";
