<!--
  Image Generation surface — explains and demonstrates what the module does
  (text-to-image + editing across pluggable providers; bytes in R2 under a
  tenant-scoped key, metadata in D1). Built on the shared DS; the gallery + handlers
  are host-supplied. Thumbnails here are deterministic gradients derived from the
  prompt — a placeholder, NOT a faked provider result — so the surface renders with
  no live model. Aspect ratio drives the thumbnail shape. Reused by the harness.
-->
<script lang="ts">
  import { Eyebrow, Button } from "@microservices-sh/ui";

  type Aspect = "1:1" | "3:4" | "4:3" | "9:16" | "16:9";
  type ProviderId = "kie-ai" | "gemini" | "gpt-image";
  type Img = { id: string; prompt: string; provider: ProviderId; aspectRatio: Aspect; key: string; tokensUsed: number; source: "studio" | "agent" | "api"; status: "active" | "deleted"; seed: number; edited?: boolean };

  let {
    providers = [],
    aspects = [],
    images = [],
    defaultProvider = "kie-ai",
    busy = false,
    ongenerate,
    onedit,
    ondelete
  }: {
    providers?: { id: ProviderId; label: string }[];
    aspects?: Aspect[];
    images?: Img[];
    defaultProvider?: ProviderId;
    busy?: boolean;
    ongenerate?: (input: { prompt: string; negativePrompt: string; aspectRatio: Aspect; provider: ProviderId }) => void;
    onedit?: (imageId: string) => void;
    ondelete?: (imageId: string) => void;
  } = $props();

  let prompt = $state("A neon koi swimming through a circuit board, cinematic");
  let negativePrompt = $state("blurry, text, watermark");
  let aspectRatio = $state<Aspect>("1:1");
  let provider = $state<ProviderId>("kie-ai");
  // Default the provider selection to the host's configured default, once.
  let providerSeeded = false;
  $effect(() => {
    if (!providerSeeded && defaultProvider) { provider = defaultProvider; providerSeeded = true; }
  });

  const ASPECT_CSS: Record<Aspect, string> = { "1:1": "1 / 1", "3:4": "3 / 4", "4:3": "4 / 3", "9:16": "9 / 16", "16:9": "16 / 9" };
  // Deterministic gradient from the seed — a placeholder thumbnail, not a real image.
  const grad = (seed: number) => {
    const h1 = seed % 360, h2 = (seed * 7 + 120) % 360;
    return `linear-gradient(135deg, hsl(${h1} 80% 58%), hsl(${h2} 75% 45%))`;
  };
  const num = (n: number) => new Intl.NumberFormat("en").format(n);
  const active = $derived(images.filter((i) => i.status === "active"));
  const PROVIDER_LABEL: Record<ProviderId, string> = { "kie-ai": "kie.ai", gemini: "Gemini", "gpt-image": "GPT-image" };

  function generate(e: Event) {
    e.preventDefault();
    if (!prompt.trim()) return;
    ongenerate?.({ prompt: prompt.trim(), negativePrompt: negativePrompt.trim(), aspectRatio, provider });
  }
</script>

<header class="ig-head">
  <Eyebrow>Image generation</Eyebrow>
  <h1 class="ig-title">Image Generation</h1>
  <p class="ig-lede">Text-to-image and editing across <strong>pluggable providers</strong> (kie.ai, Gemini, GPT-image). Generated bytes live in <strong>R2 under a tenant-scoped key</strong>, gallery metadata in D1; editing produces a <strong>new image record</strong>, and a default provider with fallback keeps generation resilient.</p>
  <ol class="ig-how">
    <li><span class="ig-how__n mono">01</span><span><strong>Generate</strong> — prompt + aspect + provider; bytes → R2, metadata → D1; emits <code>image.generated</code>.</span></li>
    <li><span class="ig-how__n mono">02</span><span><strong>Edit</strong> — re-prompt an existing image into a new record; emits <code>image.edited</code>.</span></li>
    <li><span class="ig-how__n mono">03</span><span><strong>Gallery</strong> — tenant-scoped library; removing emits <code>image.deleted</code>.</span></li>
  </ol>
</header>

<section class="ig-studio" aria-label="Generate an image">
  <div class="ig-studio__rail" aria-hidden="true"></div>
  <form class="ig-form" onsubmit={generate}>
    <label class="ig-f"><span>Prompt</span><textarea bind:value={prompt} rows="2"></textarea></label>
    <label class="ig-f"><span>Negative prompt</span><input bind:value={negativePrompt} /></label>
    <div class="ig-row">
      <div class="ig-f ig-f--inline">
        <span>Aspect</span>
        <div class="ig-aspects">
          {#each aspects as a}
            <button type="button" class="ig-ar" class:on={a === aspectRatio} onclick={() => (aspectRatio = a)}>{a}</button>
          {/each}
        </div>
      </div>
      <label class="ig-f ig-f--inline"><span>Provider</span>
        <select bind:value={provider}>
          {#each providers as p}<option value={p.id}>{p.label}{p.id === defaultProvider ? " · default" : ""}</option>{/each}
        </select>
      </label>
      <Button type="submit" variant="primary" disabled={busy}>{busy ? "Generating…" : "Generate →"}</Button>
    </div>
  </form>
</section>

<div class="ig-out">
  <p class="ig-out__h mono">Gallery <span>({active.length})</span></p>
  {#if active.length}
    <ul class="ig-grid">
      {#each active as img (img.id)}
        <li class="ig-card">
          <div class="ig-thumb" style={`aspect-ratio:${ASPECT_CSS[img.aspectRatio]}; background:${grad(img.seed)}`}>
            <span class="ig-thumb__ar mono">{img.aspectRatio}</span>
            {#if img.edited}<span class="ig-thumb__edited mono">edited</span>{/if}
          </div>
          <div class="ig-card__body">
            <p class="ig-card__prompt">{img.prompt}</p>
            <div class="ig-card__meta">
              <span class="ig-prov mono">{PROVIDER_LABEL[img.provider]}</span>
              <span class="ig-card__tok mono">{num(img.tokensUsed)} tok</span>
              <span class="ig-card__src mono">{img.source}</span>
            </div>
            <p class="ig-card__key mono">{img.key}</p>
            <div class="ig-card__actions">
              <button type="button" class="ig-act" disabled={busy} onclick={() => onedit?.(img.id)}>Edit →</button>
              <button type="button" class="ig-act ig-act--del" onclick={() => ondelete?.(img.id)}>Delete</button>
            </div>
          </div>
        </li>
      {/each}
    </ul>
  {:else}
    <p class="ig-empty">Generate an image to start your gallery.</p>
  {/if}
</div>

<style>
  .ig-head { margin-bottom: 1.5rem; }
  .ig-title { font-family: var(--font-display); font-weight: 800; font-size: clamp(1.7rem, 3vw, 2.3rem); letter-spacing: -0.02em; margin: 0.35rem 0 0.5rem; }
  .ig-lede { color: var(--color-ink-soft); max-width: 68ch; margin: 0 0 0.9rem; font-size: 1rem; }
  .ig-lede strong { color: var(--color-ink); font-weight: 600; }
  .ig-how { list-style: none; margin: 0; padding: 0; display: grid; gap: 0.5rem; max-width: 78ch; }
  .ig-how li { display: grid; grid-template-columns: auto 1fr; gap: 0.7rem; align-items: baseline; font-size: 0.9rem; color: var(--color-ink-soft); }
  .ig-how strong { color: var(--color-ink); font-weight: 600; }
  .ig-how code { font-family: var(--font-mono); color: var(--color-green); font-size: 0.86em; }
  .ig-how__n { color: var(--color-green); font-size: 0.72rem; }

  .ig-studio { position: relative; border: 1px solid var(--color-line-strong); border-radius: 14px; background: linear-gradient(180deg, var(--color-panel), var(--color-panel-subtle)); padding: 1.1rem 1.2rem 1.2rem 1.4rem; overflow: hidden; margin-bottom: 1.4rem; }
  .ig-studio__rail { position: absolute; inset: 0 auto 0 0; width: 3px; background: linear-gradient(180deg, var(--color-green), transparent); opacity: 0.7; }
  .ig-form { display: grid; gap: 0.7rem; }
  .ig-f { display: grid; gap: 0.25rem; }
  .ig-f span { font-size: 0.64rem; text-transform: uppercase; letter-spacing: 0.05em; color: var(--color-ink-faint); font-weight: 600; }
  .ig-f textarea, .ig-f input, .ig-f select { width: 100%; background: var(--color-paper); border: 1px solid var(--color-line-strong); color: var(--color-ink); border-radius: 8px; padding: 0.5rem 0.65rem; font: inherit; font-size: 0.88rem; resize: vertical; }
  .ig-f textarea:focus, .ig-f input:focus, .ig-f select:focus { outline: none; border-color: var(--color-green); box-shadow: 0 0 0 3px color-mix(in srgb, var(--color-green) 16%, transparent); }
  .ig-row { display: flex; gap: 0.9rem; align-items: end; flex-wrap: wrap; }
  .ig-f--inline { gap: 0.3rem; }
  .ig-aspects { display: flex; gap: 0.3rem; }
  .ig-ar { font: inherit; font-size: 0.74rem; font-family: var(--font-mono); background: var(--color-paper); border: 1px solid var(--color-line-strong); color: var(--color-ink-soft); border-radius: 7px; padding: 0.35rem 0.5rem; cursor: pointer; }
  .ig-ar.on { border-color: var(--color-green); color: var(--color-green); background: color-mix(in srgb, var(--color-green) 8%, var(--color-paper)); }

  .ig-out__h { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.08em; color: var(--color-ink-faint); margin: 0 0 0.6rem; }
  .ig-empty { color: var(--color-ink-faint); font-size: 0.85rem; }

  .ig-grid { list-style: none; margin: 0; padding: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(190px, 1fr)); gap: 0.8rem; }
  .ig-card { border: 1px solid var(--color-line-strong); border-radius: 12px; overflow: hidden; background: var(--color-paper); display: flex; flex-direction: column; }
  .ig-thumb { position: relative; width: 100%; max-height: 240px; display: grid; place-items: end start; padding: 0.5rem; }
  .ig-thumb__ar { font-size: 0.64rem; color: rgba(255,255,255,0.92); background: rgba(0,0,0,0.28); border-radius: 5px; padding: 0.1rem 0.35rem; }
  .ig-thumb__edited { position: absolute; top: 0.5rem; right: 0.5rem; font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.05em; color: #fff; background: rgba(0,0,0,0.4); border-radius: 5px; padding: 0.12rem 0.4rem; }
  .ig-card__body { padding: 0.6rem 0.7rem; display: grid; gap: 0.35rem; }
  .ig-card__prompt { font-size: 0.8rem; font-weight: 500; margin: 0; display: -webkit-box; -webkit-line-clamp: 2; line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
  .ig-card__meta { display: flex; flex-wrap: wrap; gap: 0.4rem; align-items: center; }
  .ig-prov { font-size: 0.64rem; color: var(--color-green); border: 1px solid color-mix(in srgb, var(--color-green) 30%, transparent); border-radius: 5px; padding: 0.08rem 0.35rem; }
  .ig-card__tok, .ig-card__src { font-size: 0.66rem; color: var(--color-ink-faint); }
  .ig-card__key { font-size: 0.6rem; color: var(--color-ink-faint); margin: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .ig-card__actions { display: flex; gap: 0.4rem; margin-top: 0.2rem; }
  .ig-act { flex: 1; font: inherit; font-size: 0.74rem; background: transparent; border: 1px solid var(--color-line-strong); color: var(--color-ink-soft); border-radius: 7px; padding: 0.3rem 0.4rem; cursor: pointer; }
  .ig-act:hover:not(:disabled) { border-color: var(--color-green); color: var(--color-green); }
  .ig-act--del:hover { border-color: #e9b8b8; color: #9b2c2c; }
</style>
